rem ECHO 1(%1) 2(%2) 3(%3) 4(%4)
IF NOT (%2)==() echo copying (%1) to (%2) ...
IF NOT (%2)==() copy /y %1 %2 
IF NOT (%3)==() echo copying (%1) to (%3) ...
IF NOT (%3)==() copy /y %1 %3
IF NOT (%4)==() echo copying (%1) to (%4) ...
IF NOT (%4)==() copy /y %1 %4
